#!/bin/sh
#
#  fbp - The missing parser for FastBasic
#
#  Cross-checks fbp against the real FastBasic compiler: compiles each
#  program and the fbp outputs with the FastBasic cross compiler, and checks
#  that the generated bytecode is the same (ignoring variable names).
#
#  Usage: tests/crosscheck.sh /path/to/fastbasic-source [files.bas...]
#
#  Without files, uses all programs in the FastBasic testsuite and samples.
#  The FastBasic compiler is built from the given source tree, only a C++
#  compiler is needed.
#
set -e

if [ $# -lt 1 ] || [ ! -f "$1/src/compiler/main.cc" ]; then
    echo "Usage: $0 /path/to/fastbasic-source [files.bas...]" >&2
    exit 1
fi
FB="$(cd "$1" && pwd)"
shift
TOP="$(cd "$(dirname "$0")/.." && pwd)"
FBP="$TOP/build/fbp"
W="$TOP/build/crosscheck"

rm -rf "$W"
mkdir -p "$W/src"

# Build FastBasic cross compiler
echo "Building FastBasic compiler..."
c++ -std=c++17 -O2 -DVERSION='"crosscheck"' -o "$W/fastbasic" \
    $(ls "$FB"/src/compiler/*.cc | grep -v -e syntp.cc -e synt-emit-asm.cc)

FBC="$W/fastbasic -syntax-path:$FB/src/syntax -target-path:$FB/compiler"

if [ $# -eq 0 ]; then
    cp "$FB"/testsuite/tests/* "$W/src/"
    cp "$FB"/samples/*/*.bas "$W/src/"
else
    cp "$@" "$W/src/"
fi

# Normalize assembly output: removes line labels and names
normalize() {
    sed -e '/^@FastBasic_LINE_/d' \
        -e '/^fb_var_/d' -e '/\.export.fb_var_/d' \
        -e 's/makevar.*/makevar/' \
        -e 's/fb_lbl_[A-Za-z0-9_]*/fb_lbl/g' "$1"
}

total=0
fail=0
cd "$W/src"
for f in *.bas; do
    b="${f%.bas}"
    chk="$b.chk"
    tgt=default
    if [ -f "$chk" ]; then
        if grep -q '^Test: compile-error' "$chk"; then
            continue
        fi
        if grep -q '^Test: .*int' "$chk"; then
            tgt=atari-int
        fi
    fi
    for mode in l s sO SX S lF; do
        case $mode in
            l)  opt="-l";    fbopt="-n" ;;
            s)  opt="-s";    fbopt="-n" ;;
            sO) opt="-s -O"; fbopt="" ;;
            # Without the optimizations that change the code
            SX) opt="-S -O -const_replace -O -chr_str -O -inc_dec"; fbopt="" ;;
            # With all optimizations, only checks that it compiles
            S)  opt="-S";    fbopt="" ;;
            lF) opt="-l -O +fixed_vars"; fbopt="" ;;
        esac
        total=$((total + 1))
        out="$b.fbp-$mode.bas"
        if ! $FBP -q -t $tgt $opt -o "$out" "$f"; then
            echo "FAIL (fbp error): $f [$opt]"
            fail=$((fail + 1))
            continue
        fi
        # Compile original and output
        $FBC -t:$tgt $fbopt -c "$f" > /dev/null 2>&1 || {
            echo "SKIP (original does not compile): $f"; continue; }
        if ! $FBC -t:$tgt $fbopt -c "$out" > "$b.err" 2>&1; then
            echo "FAIL (output does not compile): $f [$opt]"
            cat "$b.err"
            fail=$((fail + 1))
            continue
        fi
        if [ $mode = S ] || [ $mode = lF ]; then
            continue
        fi
        normalize "$b.asm" > "$b.orig.n"
        normalize "$b.fbp-$mode.asm" > "$b.new.n"
        if ! cmp -s "$b.orig.n" "$b.new.n"; then
            echo "FAIL (different code): $f [$opt]"
            diff "$b.orig.n" "$b.new.n" | head -10
            fail=$((fail + 1))
        fi
    done
done
echo "Cross-check: $total tests, $fail failures."
[ $fail -eq 0 ]
