/*
 *  fbp - The missing parser for FastBasic
 *  Copyright (C) 2026 Kim Slawson
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program.  If not, see <http://www.gnu.org/licenses/>
 */

// embed.cc: build tool, converts the FastBasic syntax and target files to a
//           C++ source file so they are included inside the fbp executable.
//
// Usage: embed output.cc file1 [file2 ...]

#include <fstream>
#include <iostream>
#include <string>

static std::string base_name(const std::string &path)
{
    auto p = path.find_last_of("/\\");
    return p == std::string::npos ? path : path.substr(p + 1);
}

int main(int argc, char **argv)
{
    if(argc < 3)
    {
        std::cerr << "usage: embed output.cc files...\n";
        return 1;
    }
    std::ofstream out(argv[1], std::ios::binary);
    if(!out)
    {
        std::cerr << "embed: can't create '" << argv[1] << "'\n";
        return 1;
    }
    out << "// Generated by tools/embed.cc - do not edit\n"
           "#include \"embedded.h\"\n\n";
    for(int i = 2; i < argc; i++)
    {
        std::ifstream in(argv[i], std::ios::binary);
        if(!in)
        {
            std::cerr << "embed: can't read '" << argv[i] << "'\n";
            return 1;
        }
        out << "static const char file_" << i << "[] = {";
        int c, n = 0;
        while((c = in.get()) != EOF)
        {
            if(n++ % 16 == 0)
                out << "\n ";
            out << ' ' << int(static_cast<unsigned char>(c)) << ',';
        }
        out << " 0\n};\n\n";
    }
    out << "const embedded_file embedded_files[] = {\n";
    for(int i = 2; i < argc; i++)
        out << "    {\"" << base_name(argv[i]) << "\", file_" << i << "},\n";
    out << "    {nullptr, nullptr}\n};\n";
    return 0;
}
